<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <Configurations>Debug;Deploy;Release;SandBox</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\Westwind.MessageQueueing.Hosting.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.Owin.Host.SystemWeb">
      <HintPath>..\..\..\..\Clients\MarvelPress\Marvel-Press-Workflow\packages\Microsoft.Owin.Host.SystemWeb.3.0.1\lib\net45\Microsoft.Owin.Host.SystemWeb.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Westwind.MessageQueueing\Westwind.MessageQueueing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Cors" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNet.Razor" Version="3.2.2" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Owin" Version="1.2.2" />
    <PackageReference Include="Microsoft.AspNet.SignalR.SystemWeb" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNet.WebPages" Version="3.2.2" />
    <PackageReference Include="Microsoft.Owin" Version="3.0.1" />
    <PackageReference Include="Microsoft.Owin.Cors" Version="3.0.0" />
    <PackageReference Include="Microsoft.Owin.Host.SystemWeb" Version="3.0.1" />
    <PackageReference Include="Microsoft.Owin.Security" Version="3.0.1" />
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="1.0.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="7.0.1" />
    <PackageReference Include="Owin" Version="1.0" />
    <PackageReference Include="Westwind.Utilities" Version="2.64" />
  </ItemGroup>
</Project>